import paho.mqtt.client as mqtt
mqttc = mqtt.Client("python_pub")
mqttc.connect('localhost', 1883)
mqttc.publish("orchestra/speed", 559)

mqttc.connect('localhost', 1883)
mqttc.publish("orchestra/skutter_18:FE:34:FD:91:AD", 1)
mqttc.connect('localhost', 1883)
mqttc.publish("orchestra/skutter_18:FE:34:FD:92:D1", 1)
mqttc.connect('localhost', 1883)
mqttc.publish("orchestra/skutter_5C:CF:7F:0E:2C:EA", 1)
mqttc.connect('localhost', 1883)
mqttc.publish("orchestra/skutter_18:FE:34:F4:D3:BD", 1)
mqttc.connect('localhost', 1883)
mqttc.publish("orchestra/twitch", 1)